\ProvidesClass{+}
\NeedsTeXFormat{LaTeX2e}[1995/06/01]
\LoadClass{article}

\RequirePackage[active,tightpage]{preview}
\RequirePackage{tikz}


%% the following commands are sometimes needed
\usetikzlibrary{angles}
\usetikzlibrary{arrows}
\usetikzlibrary{calc}
\usetikzlibrary{decorations.pathmorphing}
\usetikzlibrary{decorations.shapes}
\usetikzlibrary{decorations}
\usetikzlibrary{fadings}
\usetikzlibrary{intersections}
\usetikzlibrary{matrix}
\usetikzlibrary{patterns}
\usetikzlibrary{plotmarks}
\usetikzlibrary{positioning}
\usetikzlibrary{quotes}
\usetikzlibrary{spy}
\usetikzlibrary{through}

\PreviewEnvironment{tikzpicture}
\tikzset{font={\fontsize{8pt}{12}\selectfont}}

\definecolor{imR}{RGB}{165,30,55}
\definecolor{imD}{RGB}{10,41,62}
\definecolor{imB}{RGB}{61,155,232}
