INSERT INTO users  (
  id,
  created_at,
  updated_at,
  first_name,
  last_name,
  avatar_path,
  email,
  student_number,
  semester,
  subject,
  language,
  encrypted_password,
  reset_password_token,
  confirm_email_token,
  root
)
VALUES(
  DEFAULT,
  current_timestamp,
  current_timestamp,
  'TestV',
  'TestN',
  NULL,
  'test@uni-tuebingen.de',
  0815,
  1,
  'mathematics',
  'en',
  '$2a$10$PJqjI61.2f7n6t1drJcIMuv7k.emMbvPutmy3JYg.93MzikgmVbbK',
  NULL,
  NULL,
  TRUE
);