{
 "title": "InfoMark System",
 "time": { "from": "now-30d", "to": "now" },
 "panels": [
  {
   "title": "submissions which are queued and ended",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(worker_submissions_success_total)/(sum(worker_submissions_pushed_total)*2)*100"
    }
   ]
  },
  {
   "title": "Docker Successful Private Test",
   "type": "singlestat",
   "description": "docker has exit code 0",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(worker_submissions_success_total{kind=\"private\"})"
    }
   ]
  },
  {
   "title": "Docker Failed Private Test",
   "type": "singlestat",
   "description": "docker has exit code != 0",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(worker_submissions_failed_total{kind=\"private\"})"
    }
   ]
  },
  {
   "title": "Authentification",
   "type": "graph",
   "description": "number of times, when username was correct but password was wrong",
   "gridPos": { "h": 6, "w": 8, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(auth_logins_failed_logins[5m])) ",
     "legendFormat": "failed_logins"
    }
   ]
  },
  {
   "title": "Total wrong passwords",
   "type": "singlestat",
   "description": "correct user but wrong password",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "sum(auth_logins_failed_logins)" }
   ]
  },
  {
   "title": "Docker Successful Public Test",
   "type": "singlestat",
   "description": "docker has exit code 0",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 3 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(worker_submissions_success_total{kind=\"public\"})"
    }
   ]
  },
  {
   "title": "Docker Failed Public Test",
   "type": "singlestat",
   "description": "docker has exit code != 0",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 3 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(worker_submissions_failed_total{kind=\"public\"})"
    }
   ]
  },
  {
   "title": "Total wrong passwords / hour",
   "type": "singlestat",
   "description": "correct user but wrong password",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 3 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(increase(auth_logins_failed_logins[1h]))"
    }
   ]
  },
  {
   "title": "Submissions / hour",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(increase(worker_submissions_pushed_total[1h]))"
    }
   ]
  },
  {
   "title": "max Submissions / hour",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 6 },
   "format": "none",
   "valueName": "max",
   "targets": [
    {
     "expr": "sum(increase(worker_submissions_pushed_total[1h]))"
    }
   ]
  },
  {
   "title": "avg Submissions / hour",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 6 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(increase(worker_submissions_pushed_total[1h]))"
    }
   ]
  },
  {
   "title": "submitted Submissions",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(worker_submissions_pushed_total)"
    }
   ]
  },
  {
   "title": "Submissions",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 6 },
   "targets": [
    {
     "expr": "worker_submissions_pushed_total"
    }
   ]
  },
  {
   "title": "Time-Benchmark (95 Quantile)",
   "type": "graph",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "s", "label": "time" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(worker_submissions_totalTime_bucket[5m])) by (le))",
     "legendFormat": "from upload to result"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(worker_submissions_totalWaitTime_bucket[5m])) by (le))",
     "legendFormat": "from upload to docker test"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(worker_submissions_totalRunTime_bucket[5m])) by (le))",
     "legendFormat": "inside docker test"
    }
   ]
  },
  {
   "title": "Worker Queue / 30min",
   "type": "graph",
   "description": "submitted testing jobs on queue",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(worker_submissions_failed_total{kind=\"private\"}[30m]))",
     "legendFormat": "private failed"
    },
    {
     "expr": "sum(rate(worker_submissions_failed_total{kind=\"public\"}[30m]))",
     "legendFormat": "public failed"
    },
    {
     "expr": "sum(rate(worker_submissions_success_total{kind=\"private\"}[30m]))",
     "legendFormat": "private succeeded"
    },
    {
     "expr": "sum(rate(worker_submissions_success_total{kind=\"private\"}[30m]))",
     "legendFormat": "public succeeded"
    }
   ]
  },
  {
   "title": "Submissions per task",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(worker_submissions_pushed_total) by (task_id)"
    }
   ]
  },
  {
   "title": "Distribution of total uploads per task",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "short", "label": "Uploads" }
   ],
   "targets": [
    {
     "expr": "sum(worker_submissions_pushed_total) by (task_id)"
    }
   ]
  }
 ]
}